### ISSUE TITLE
I think commonJS and CMD is different

### ISSUE THREAD

**Issue by frankxin** [nqdeng/7-days-nodejs#22]
There is a description in your article .
> ![image](https://cloud.githubusercontent.com/assets/6349036/8587958/744f52ec-2636-11e5-8c71-4d5c84334620.png)

And May be I can't agree with you about that so .
I think commonJS is not CMD.
CMD is the product ，which comes along with seaJS.
>  https://github.com/seajs/seajs/issues/242

And commonJS standard is nodeJS follow on .
So I think your description will mislead learner .
Is it that right?
Feel free to contact me , to feature out my mistake.
Thank you.

**Comment by bigggge** [comment]
不是应该是CommonJS吗，为什么是CMD，不太理解这两者联系？
